name: Run Selenium Test

on:
  schedule:
    - cron: '*/2 * * * *'  # Hər 15 dəqiqədə bir işə düşür
  workflow_dispatch:  # Manual olaraq işə salına bilər

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Depodakı faylları klonlayır

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Python versiyası

      - name: Install Dependencies
        run: |
          pip install selenium  # Selenium kitabxanasını quraşdırır
          sudo apt-get update  # Sistem yenilənməsi
          sudo apt-get install -y chromium-chromedriver  # Chrome və ChromeDriver-i quraşdırır
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver  # ChromeDriver-in yolunu təyin edir

      - name: Run Selenium Script
        run: python visit_page.py  # Selenium skriptini işlədir
