name: Visit Page Workflow

on:
  schedule:
    - cron: '*/1 * * * *'  # Hər 15 dəqiqədə bir icra ediləcək
  workflow_dispatch:  # Lazım olsa manual olaraq işə salına bilər

jobs:
  visit-page:
    runs-on: ubuntu-latest  # Ubuntu mühitində işləyəcək

    steps:
      - name: Visit Page with Headers
        run: |
          curl -H "User-Agent: GitHubActions" \
               -H "Accept: text/html" \
               -b "__test=1759c0b2cc931d85f96464b9dced7e0c; PHPSESSID=66c311fe424a87b9dd83871097adaf3e" \
               https://wp.pavilion.az/send_reminder.php
