name: Visit Page Workflow

on:
  schedule:
    - cron: '*/1 * * * *'  # Hər 15 dəqiqədə bir icra ediləcək
  workflow_dispatch:  # Manual işə salmaq üçün

jobs:
  visit-page:
    runs-on: ubuntu-latest  # Ubuntu mühitində işləyəcək

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Depodakı faylları klonlayır

      - name: Visit Page with Curl
        run: |
          curl -I https://wp.pavilion.az/send_reminder.php  # Header-ları yoxlamaq üçün
          curl https://wp.pavilion.az/send_reminder.php  # Saytı ziyarət edir və məzmunu göstərir
